openapi: 3.1.0

info:
  title: OpenGIN Service API - Gazette
  description: This document gives the structure of APIs for the OpenGIN Gazette Services.
  version: 1.0.0

servers:
  - url: http://localhost:8081

tags:
  - name: Gazette
    description: APIs for Gazette

paths:
  /v1/gazette/data-points:
    get:
      tags:
        - Gazette
      summary: Get gazette data points.
      description: Returns number of gazettes created for each month for all years.
      operationId: getGazetteDataPoints
      responses:
        "200":
          description: Successfully returned
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: integer
                  minItems: 12
                  maxItems: 12
              example:
                "2023": [10, 5, 8, 12, 7, 9, 11, 6, 4, 15, 13, 14]
                "2024": [12, 8, 10, 15, 9, 11, 13, 7, 5, 18, 16, 17]

        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Server Error
